// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PwnLearn.Data;

#nullable disable

namespace PwnLearn.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PwnLearn.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fundamentals",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Core concepts of information security: CIA triad, threat landscape, attack surfaces, and defence strategies.",
                            Difficulty = "Beginner",
                            IconEmoji = "🛡️",
                            IsPublished = true,
                            Title = "Cybersecurity Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Get comfortable with Kali Linux — the industry-standard penetration-testing distribution.",
                            Difficulty = "Beginner",
                            IconEmoji = "🐉",
                            IsPublished = true,
                            Title = "Kali Linux Essentials"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Learn to use Metasploit for vulnerability assessment and controlled exploitation in lab environments.",
                            Difficulty = "Intermediate",
                            IconEmoji = "⚡",
                            IsPublished = true,
                            Title = "Metasploit Framework"
                        },
                        new
                        {
                            Id = 4,
                            Category = "CTF",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Introduction to Capture-the-Flag competitions: web exploitation, reverse engineering, and cryptography.",
                            Difficulty = "Intermediate",
                            IconEmoji = "🚩",
                            IsPublished = true,
                            Title = "CTF Challenges & Strategy"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fundamentals",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Understand the legal and ethical framework around penetration testing and vulnerability reporting.",
                            Difficulty = "Beginner",
                            IconEmoji = "⚖️",
                            IsPublished = true,
                            Title = "Ethical Hacking & Responsible Disclosure"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tools",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master Nmap, Wireshark, and passive OSINT techniques for network discovery.",
                            Difficulty = "Advanced",
                            IconEmoji = "🔍",
                            IsPublished = true,
                            Title = "Network Reconnaissance"
                        });
                });

            modelBuilder.Entity("PwnLearn.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletedModules")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedModules = 1,
                            CourseId = 1,
                            EnrolledAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PwnLearn.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Confidentiality, Integrity, and Availability form the cornerstone of information security. Every security control can be mapped back to protecting one or more of these three properties. Confidentiality prevents unauthorised disclosure; Integrity ensures data is not tampered with; Availability guarantees that systems and data are accessible when needed.",
                            CourseId = 1,
                            OrderIndex = 1,
                            Title = "The CIA Triad"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Understanding who attacks systems and why is essential for building effective defences. Threat actors range from script kiddies and hacktivists to nation-state APT groups. Motivations include financial gain, espionage, ideological causes, and notoriety. Mapping actors to the MITRE ATT&CK framework helps defenders anticipate tactics.",
                            CourseId = 1,
                            OrderIndex = 2,
                            Title = "Threat Actors & Motivations"
                        },
                        new
                        {
                            Id = 3,
                            Content = "An attack surface is the sum of all points where an attacker could try to enter or extract data from a system. Common vectors include phishing, unpatched software, weak credentials, and misconfigured cloud resources. Reducing the attack surface through least privilege, patch management, and network segmentation is a primary defensive strategy.",
                            CourseId = 1,
                            OrderIndex = 3,
                            Title = "Attack Surfaces & Vectors"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Kali Linux can be installed as a VM (VirtualBox/VMware), run live from USB, or deployed in WSL on Windows. After installation, update the package list with `sudo apt update && sudo apt upgrade`. The default toolset includes over 600 security tools pre-configured and ready to use.",
                            CourseId = 2,
                            OrderIndex = 1,
                            Title = "Installing & Configuring Kali"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Mastery of the Linux terminal is non-negotiable for penetration testers. Key commands: `ls`, `cd`, `cat`, `grep`, `find`, `chmod`, `netstat`, `ps`, and `kill`. Piping (`|`) and redirection (`>`, `>>`) allow powerful one-liners. Practice building compound commands to automate reconnaissance tasks.",
                            CourseId = 2,
                            OrderIndex = 2,
                            Title = "Essential Terminal Commands"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Metasploit Framework consists of modules: Exploits, Payloads, Auxiliaries, Encoders, and Post-exploitation modules. The `msfconsole` is the primary interface. Understanding the difference between a bind shell and a reverse shell payload is fundamental before running any module.",
                            CourseId = 3,
                            OrderIndex = 1,
                            Title = "Metasploit Architecture"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Using a controlled Metasploitable VM, we practice the full exploitation cycle: `search`, `use`, `set RHOSTS`, `set PAYLOAD`, `run`. Always confirm you have written permission before testing any system. Document your findings in a structured report with steps to reproduce and suggested remediation.",
                            CourseId = 3,
                            OrderIndex = 2,
                            Title = "Your First Exploit (Lab)"
                        });
                });

            modelBuilder.Entity("PwnLearn.Models.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("PwnLearn.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoicesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoicesJson = "[\"Confidentiality\",\"Integrity\",\"Availability\",\"Authentication\"]",
                            CorrectIndex = 2,
                            Explanation = "Availability guarantees that systems and data remain accessible to authorised users. DDoS attacks typically target availability.",
                            ModuleId = 1,
                            QuestionText = "Which element of the CIA triad ensures that information is accessible to authorised users when needed?"
                        },
                        new
                        {
                            Id = 2,
                            ChoicesJson = "[\"Integrity\",\"Availability\",\"Confidentiality\",\"Non-repudiation\"]",
                            CorrectIndex = 2,
                            Explanation = "Reading private data without authorisation violates Confidentiality — the property that prevents unauthorised disclosure of information.",
                            ModuleId = 1,
                            QuestionText = "A hacker intercepts network traffic and reads private emails without modifying them. Which CIA property has been violated?"
                        },
                        new
                        {
                            Id = 3,
                            ChoicesJson = "[\"Confidentiality\",\"Availability\",\"Integrity\",\"Accountability\"]",
                            CorrectIndex = 1,
                            Explanation = "Ransomware primarily attacks Availability by making data inaccessible. Some attacks also impact Integrity by modifying files.",
                            ModuleId = 1,
                            QuestionText = "A ransomware attack encrypts files so the owner can no longer open them. Which CIA property is primarily affected?"
                        },
                        new
                        {
                            Id = 4,
                            ChoicesJson = "[\"sudo apt upgrade\",\"sudo apt update\",\"sudo apt install\",\"sudo apt refresh\"]",
                            CorrectIndex = 1,
                            Explanation = "`sudo apt update` fetches the latest package information from repositories. It does not install or upgrade packages — that's `apt upgrade`.",
                            ModuleId = 4,
                            QuestionText = "Which command updates the package list on a Kali Linux system?"
                        },
                        new
                        {
                            Id = 5,
                            ChoicesJson = "[\"VirtualBox\",\"VMware\",\"WSL (Windows Subsystem for Linux)\",\"Docker Desktop\"]",
                            CorrectIndex = 2,
                            Explanation = "WSL2 with a Kali Linux distribution from the Microsoft Store lets you run Kali tools directly inside Windows without a full VM overhead.",
                            ModuleId = 4,
                            QuestionText = "Which virtualisation option allows running Kali Linux on Windows without a full virtual machine?"
                        });
                });

            modelBuilder.Entity("PwnLearn.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pwnlearn.io",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$cnoswt/QTctj7ElAQUC6xezDCqu9TGoAbcdaJby0kDnS05kAgPvMG",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@pwnlearn.io",
                            IsActive = true,
                            Name = "Demo Member",
                            PasswordHash = "$2a$11$kIZ9znlLyQm9NdMPkMb41OecQPMch8UCw1.m.uyEo4naTBK0ZpH26",
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("PwnLearn.Models.Enrollment", b =>
                {
                    b.HasOne("PwnLearn.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PwnLearn.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PwnLearn.Models.Module", b =>
                {
                    b.HasOne("PwnLearn.Models.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PwnLearn.Models.QuizAttempt", b =>
                {
                    b.HasOne("PwnLearn.Models.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PwnLearn.Models.User", "User")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PwnLearn.Models.QuizQuestion", b =>
                {
                    b.HasOne("PwnLearn.Models.Module", "Module")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("PwnLearn.Models.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("PwnLearn.Models.Module", b =>
                {
                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("PwnLearn.Models.User", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
